export const ROUTER = 'EQAN-TONIOdpazUG5aSecU3MA2Ch6qTSvan9qJJ1JVuP1gO1';
export const pTON_MINTER = 'EQBlde83gVhXQKGogwCxKbiyB37N5K0mX4YcC9XTR1iFX1iO';
export const pTON_ROUTER_WALLET =
  'EQBYbd1sKmbSpDaUNuvqMEIoY0VCKA391sDmX_VqdOfexFuM';
