export const ROUTER = 'EQBO-T0NCODKT87McOAK2Vb-Whx_jLFHU5NCDBJYkBcsil9s';
export const pTON_MINTER = 'EQBlde83gVhXQKGogwCxKbiyB37N5K0mX4YcC9XTR1iFX1iO';
export const pTON_ROUTER_WALLET =
  'EQDvHepUtqEvHjlAWL9cpmoTZ_LAsS9bTr8_Uum17eAMtf9L';
