import { Cell } from '@ton/core';
import { DEX_VERSION } from '../types';

interface InitCodeBase64 {
  router: string;
  pool: string;
  account: string;
  positionnft: string;
  distributor: string;
  user_distributor: string;
}

const INIT_CODE_BASE64: Record<DEX_VERSION, InitCodeBase64> = {
  [DEX_VERSION.v1]: {
    router: process.env.ROUTER_CODE,
    pool: process.env.POOL_CODE,
    account:
      'te6cckECDQEAAloAART/APSkE/S88sgLAQIBYgIMAgLNAwsCtddtF2/ZkQ44BJL4HwaGmB9qJofSAA/DD9IAD8MWoYaH0AAPwx/QAA/DJ9AAD8Mv0AGHwzALjYSS+B8H0gGADpj+mf/CEpIGOCyJhxhvwgieOCyS+B8YbCB/l4QEBwLuIoIQPr5UMbqPa2wy+gD6APoA+gDTf9IX0hcw+ENQB6D4Y/hEUAWg+GQC+GX4ZiDCAPhD+EW+sPhE+Ea+sI6yghCBcC74yMsfFMs/+EP6AvhE+gL4Qc8WE8t/EsoXyhfJ+EIB2zxw+GNw+GRw+GVw+GaSXwTi4DAFBgAscYAYyMsFUAPPFnD6AhLLaszJgwb7AABCyPhD+gL4RPoC+EX6AvhG+gLJyPhBzxb4Qs8WzMntVNsxAl4gghBCoPtDuo6YWyCCCJiWgLzy4FOCCJiWgKH4QXDbPNsx4GwSghAL8/RHuuMCMAgJAChwgBjIywVQA88WUAP6AstqyQH7AAHc+EPCAPhEwgCx8uBQgg/ydhiCCA2J6HCCEIFwLvjIyx8Uyz/4Q/oC+ET6AvhBzxYTy38SyhfKF3D4QgLJEoBA2zxw+GNw+GRw+GVw+GbI+EP6AvhE+gL4RfoC+Eb6AsnI+EHPFvhCzxbMye1U2zEKACxxgBjIywVQBM8WUAT6AhLLaszJAfsAAEnThAEUcOgOmDgNUDiVk8T5BBh1hLVQBAiBDZSVUAcXJCB9hyGMAGWgonPaiaH0gAPww/SAA/DFqGGh9AAD8Mf0AAPwyfQAA/DL9ABh8M3wg/CF8IfwifCL8I0lL38n',
    positionnft:
      'te6cckECFwEAA3gAART/APSkE/S88sgLAQIBYgIQAgLLAw8CASAEDgIBIAUNAvXRkQ44BJL4HwaGmBgLjYSS+B8H0gfSAY/QAYuOuQ/QAY/QAYOdTaAHgHgWmP6Z+RQQhq9mUVXUcXGi2ZfCEsY4L5cMr9IAD8Mem/gPwy6QuA/DNpC4D8M+oYaGn/gPw0af+YfDT4CHARQQgv5h6KXXGBGhpBCCNlGa1dQGCQLYMvhDE8cF8uGR+kD6QNIAMfoAcCSBAU0B+kQwWLry9CDXScIA8uLEBoIK+vCAoYIImJaAoSGUUxWgod4i1wsBwwAgkgahkTbiIML/8uGSIZI2MOMN+EKCCJiWgIIQ9Ydg7/hByCbPFss/UmBwBwgAeoIQBRONkcj4Q88WUAjPFnElBEkTVEegcIAQyMsFUAfPFlAF+gIVy2oSyx/LPyJus5RYzxcBkTLiAckB+wAA3nCAEMjLBVAHzxZQBfoCFctqEssfyz8ibrOUWM8XAZEy4gHJAfsAA44+cCOBAU0B+kQwWLry9BOCENUydttQBG1xcIAQyMsFUAfPFlAF+gIVy2oSyx/LPyJus5RYzxcBkTLiAckB+wCSbDHi+GPwEAEQ4wJfA4QP8vAKAf4B+kDTf9IX0hfUMNDT/9P/MPhCF8cF8uBS+EMVxwXy4ZH4RhK68uGZ+Ee68uGZ+EXAAPLRmPhFAbYIIcjL/1Iwy//J+En4SMjL/8v/yfhH+Eb4RfhBghDXOsCdyMsfGss/+EPPFhnLPxjLfxfKFxbKF1Igy38VzBTMyfhFUAShCwEy+GX4aPhpgED4RcAAkzCDBt5w+EJa2zzwEAwALHGAGMjLBVAEzxZQBPoCEstqzMkB+wAASdOEARRw6A6YOA1QOJWTxPkEGHWEtVAECIENlJVQBxckIH2HIYwAZf9qJoaZ+A/DD9IAD8MX0gAPwx6gD8Mmm/gPwy6QuA/DNpC4D8M+oYaGn/gPw0af+YfDTABV0+En4SMjL/8v/yfhH+Eb4RfhE+EHIyz/4Qs8W+EPPFszLf8oXyhfMye1UgIBIBEUAgEgEhMAHbijjwD/hF+Eb4R/hI+EmAANueGfAP+EOAIBIBUWAHO4/P8A/4RNDTBzH0BDD4SfhI+Ef4RvhFcMjLBxb0ABXLfxTKFxPKFxLL/8v/yfhFwwD4QfhC+ENVA4AA26jC8A/4Qo1aJhlg==',
    distributor:
      'te6ccgECEQEAAhoAART/APSkE/S88sgLAQIBYgIDAgLLBAUCASANDgIBYgYHAgHOCwwB7UbCIg10nBYJFb4NMfAfhk0z8B+GYB0HTXIfpAMPhl7UTQ+kAB+GHUAfhj1DDQ9AQw+GL4RIIQp2neJ7rjAvhEghDw/r5kuo4s+EH4RccF8uK/0x/T/zDIy//4QhKAIPRD+GL4Qsj0AMn4Q8j4Qc8WzMzJ7VTgMICABvQgxJgwizbmFujPFo4pbSHBAJmALVADywcBo1jenAF6qQymMFhvAiHAAOYxmG8iAssHIW4S5jDigB0tMf03/U0/8wIdc5+EJSYIAg9A5vofLiw9P/MAHyqgHTBwHAA/Kr0/9ZuvKs1DBSEIMH9A5vofKt0x9SUrry4sTTf1JCuvLixfhFA/kAVBAlJfAQMzMB8BHHBfLiv/pA+kD6ADD4RgJwWQkBUHAgghAPin6lyMsfFss/UAP6AiHPFgHPFhPLAAH6AssAcAHJEoBC2zwKACxxgBjIywVQBM8WUAT6AhLLaszJAfsAADkcMjLAPgozxYUy/8Sy//LH8t/yfhDdsjLBMzMyYAAXPkAgwnIywrL/8nQgADW/cn9qJofSAA/DDqAPwx6hhoegIYfDF4CHgIwCAWYPEABJshs7UTQ+kAB+GHUAfhj1DDQ9AQw+GL4QoAg9A5vofLiw9P/MIAAxsn27UTQ+kAB+GHUAfhj1DDQ9AQw+GL4QYA==',
    user_distributor:
      'te6cckECCQEAAQUAART/APSkE/S88sgLAQIBIAIHAgFIAwYCAs4EBQABSABvQgxJgwizbmFujPFo4pbSHBAJmALVADywcBo1jenAF6qQymMFhvAiHAAOYxmG8iAssHIW4S5jDigAEaCY19qJoa4UAQH28mwhAYIQBfXhAL7y4sDtRNDSAAH4YfpAAfhi0/8B+GPT/wH4ZNMfAfhl038B+GbR+EHy0r5x+GH4RvhF+ET4Q/hByMsA+ELPFsv/y//LH8t/ye1U0z/UMCD5APhDuvLiwfgAggr68IBx+wL4RPhG+EWCEKdp3ifIyx8VCABCyz8Uyx8Ty3/My//JcYAQyMsF+ELPFnD6AstqzMmDBvsADs7vKQ==',
  },
  [DEX_VERSION.v1_5]: {
    router: process.env.ROUTER_CODE_V1_5,
    pool: process.env.POOL_CODE_V1_5,
    account:
      'te6cckECDQEAAloAART/APSkE/S88sgLAQIBYgIMAgLNAwsCtddtF2/ZkQ44BJL4HwaGmB9qJofSAA/DD9IAD8MWoYaH0AAPwx/QAA/DJ9AAD8Mv0AGHwzALjYSS+B8H0gGADpj+mf/CEpIGOCyJhxhvwgieOCyS+B8YbCB/l4QEBwLuIoIQPr5UMbqPa2wy+gD6APoA+gDTf9IX0hcw+ENQB6D4Y/hEUAWg+GQC+GX4ZiDCAPhD+EW+sPhE+Ea+sI6yghCBcC74yMsfFMs/+EP6AvhE+gL4Qc8WE8t/EsoXyhfJ+EIB2zxw+GNw+GRw+GVw+GaSXwTi4DAFBgAscYAYyMsFUAPPFnD6AhLLaszJgwb7AABCyPhD+gL4RPoC+EX6AvhG+gLJyPhBzxb4Qs8WzMntVNsxAl4gghBCoPtDuo6YWyCCCJiWgLzy4FOCCJiWgKH4QXDbPNsx4GwSghAL8/RHuuMCMAgJAChwgBjIywVQA88WUAP6AstqyQH7AAHc+EPCAPhEwgCx8uBQgg/ydhiCCA2J6HCCEIFwLvjIyx8Uyz/4Q/oC+ET6AvhBzxYTy38SyhfKF3D4QgLJEoBA2zxw+GNw+GRw+GVw+GbI+EP6AvhE+gL4RfoC+Eb6AsnI+EHPFvhCzxbMye1U2zEKACxxgBjIywVQBM8WUAT6AhLLaszJAfsAAEnThAEUcOgOmDgNUDiVk8T5BBh1hLVQBAiBDZSVUAcXJCB9hyGMAGWgonPaiaH0gAPww/SAA/DFqGGh9AAD8Mf0AAPwyfQAA/DL9ABh8M3wg/CF8IfwifCL8I0lL38n',
    positionnft:
      'te6cckECFwEAA9AAART/APSkE/S88sgLAQIBYgIQAgLLAw8CASAEDgIBIAUNAvfRkQ44BJL4HwaGmBgLjYSS+B8H0gfSAY/QAYuOuQ/QAY/QAYOdTaAHgHgWmP6Z+RQQhq9mUVXUcXGi2ZfCEsY4L5cMr9IAD8Mem/gPwy6QuA/DNpC4D8M+oYaGl/gPw0aX+YfDT4CHARQQgv5h6KXXGBGhoQQQgjZRmtXUBgkC2DL4QxPHBfLhkfpA+kDTADH6AHAkgQFNAfpEMFi68vQg10nCAPLixAaCCvrwgKGCCJiWgKEhlFMVoKHeItcLAcMAIJIGoZE24iDC//LhkiGSNjDjDfhCggiYloCCEPWHYO/4QcgmzxbLP1JgcAcIAHqCEAUTjZHI+EPPFlAIzxZxJQRJE1RHoHCAEMjLBVAHzxZQBfoCFctqEssfyz8ibrOUWM8XAZEy4gHJAfsAAN5wgBDIywVQB88WUAX6AhXLahLLH8s/Im6zlFjPFwGRMuIByQH7AAOOPnAjgQFNAfpEMFi68vQTghDVMnbbUARtcXCAEMjLBVAHzxZQBfoCFctqEssfyz8ibrOUWM8XAZEy4gHJAfsAkmwx4vhj8BACuuMCMYIQwMUuO7qOy/pA0wD0BDABmvhJ+EjIyv/K/8mRbeL4R/hG+EX4QYIQ3t8emMjLHxjLP/hCzxb4Q88WF8s/Fst/FcoXFMoXE/QAEvQAyXBZgEDbPOBbhA/y8AoMAf4wAfpA03/SF9IX1DDQ0v/S/zD4QhfHBfLgUvhDFccF8uGR+EYSuvLhmfhHuvLhmfhFwADy0Zj4RQG2CCHIyv9SMMr/yfhJ+EjIyv/K/8n4R/hG+EX4QYIQ1zrAncjLHxrLP/hDzxYZyz8Yy38XyhcWyhdSIMt/FcwUzMn4RVAECwE0ofhl+Gj4aYBA+EXAAJMwgwbecPhCWts88BAMACxxgBjIywVQBM8WUAT6AhLLaszJAfsAAEnThAEUcOgOmDgNUDiVk8T5BBh1hLVQBAiBDZSVUAcXJCB9hyGMAGX/aiaGmfgPww/SAA/DF9IAD8MeoA/DJpv4D8MukLgPwzaQuA/DPqGGhpf4D8NGl/mHw0wAVdPhJ+EjIyv/K/8n4R/hG+EX4RPhByMs/+ELPFvhDzxbMy3/KF8oXzMntVICASARFAIBIBITAB24o48A/4RfhG+Ef4SPhJgADbnhnwD/hDgCASAVFgBzuPz/AP+ETQ0wcx9AQw+En4SPhH+Eb4RXDIywcW9AAVy38UyhcTyhcSy//L/8n4RcMA+EH4QvhDVQOAANuowvAP+EKPydzOU=',
    distributor:
      'te6ccgECEQEAAhoAART/APSkE/S88sgLAQIBYgIDAgLLBAUCASANDgIBYgYHAgHOCwwB7UbCIg10nBYJFb4NMfAfhk0z8B+GYB0HTXIfpAMPhl7UTQ+kAB+GHUAfhj1DDQ9AQw+GL4RIIQp2neJ7rjAvhEghDw/r5kuo4s+EH4RccF8uK/0x/T/zDIy//4QhKAIPRD+GL4Qsj0AMn4Q8j4Qc8WzMzJ7VTgMICABvQgxJgwizbmFujPFo4pbSHBAJmALVADywcBo1jenAF6qQymMFhvAiHAAOYxmG8iAssHIW4S5jDigB0tMf03/U0/8wIdc5+EJSYIAg9A5vofLiw9P/MAHyqgHTBwHAA/Kr0/9ZuvKs1DBSEIMH9A5vofKt0x9SUrry4sTTf1JCuvLixfhFA/kAVBAlJfAQMzMB8BHHBfLiv/pA+kD6ADD4RgJwWQkBUHAgghAPin6lyMsfFss/UAP6AiHPFgHPFhPLAAH6AssAcAHJEoBC2zwKACxxgBjIywVQBM8WUAT6AhLLaszJAfsAADkcMjLAPgozxYUy/8Sy//LH8t/yfhDdsjLBMzMyYAAXPkAgwnIywrL/8nQgADW/cn9qJofSAA/DDqAPwx6hhoegIYfDF4CHgIwCAWYPEABJshs7UTQ+kAB+GHUAfhj1DDQ9AQw+GL4QoAg9A5vofLiw9P/MIAAxsn27UTQ+kAB+GHUAfhj1DDQ9AQw+GL4QYA==',
    user_distributor:
      'te6cckECCQEAAQUAART/APSkE/S88sgLAQIBIAIHAgFIAwYCAs4EBQABSABvQgxJgwizbmFujPFo4pbSHBAJmALVADywcBo1jenAF6qQymMFhvAiHAAOYxmG8iAssHIW4S5jDigAEaCY19qJoa4UAQH28mwhAYIQBfXhAL7y4sDtRNDSAAH4YfpAAfhi0/8B+GPT/wH4ZNMfAfhl038B+GbR+EHy0r5x+GH4RvhF+ET4Q/hByMsA+ELPFsv/y//LH8t/ye1U0z/UMCD5APhDuvLiwfgAggr68IBx+wL4RPhG+EWCEKdp3ifIyx8VCABCyz8Uyx8Ty3/My//JcYAQyMsF+ELPFnD6AstqzMmDBvsADs7vKQ==',
  },
};

export const ROUTER_CODE: Record<DEX_VERSION, Cell> = {
  [DEX_VERSION.v1]: Cell.fromBase64(INIT_CODE_BASE64[DEX_VERSION.v1].router),
  [DEX_VERSION.v1_5]: Cell.fromBase64(
    INIT_CODE_BASE64[DEX_VERSION.v1_5].router
  ),
};
export const ACCOUNT_CODE: Record<DEX_VERSION, Cell> = {
  [DEX_VERSION.v1]: Cell.fromBase64(INIT_CODE_BASE64[DEX_VERSION.v1].account),
  [DEX_VERSION.v1_5]: Cell.fromBase64(
    INIT_CODE_BASE64[DEX_VERSION.v1_5].account
  ),
};
export const POSITION_CODE: Record<DEX_VERSION, Cell> = {
  [DEX_VERSION.v1]: Cell.fromBase64(
    INIT_CODE_BASE64[DEX_VERSION.v1].positionnft
  ),
  [DEX_VERSION.v1_5]: Cell.fromBase64(
    INIT_CODE_BASE64[DEX_VERSION.v1_5].positionnft
  ),
};
export const POOL_CODE: Record<DEX_VERSION, Cell> = {
  [DEX_VERSION.v1]: Cell.fromBase64(INIT_CODE_BASE64[DEX_VERSION.v1].pool),
  [DEX_VERSION.v1_5]: Cell.fromBase64(INIT_CODE_BASE64[DEX_VERSION.v1_5].pool),
};
export const DISTRIBUTOR_CODE: Record<DEX_VERSION, Cell> = {
  [DEX_VERSION.v1]: Cell.fromBase64(
    INIT_CODE_BASE64[DEX_VERSION.v1].distributor
  ),
  [DEX_VERSION.v1_5]: Cell.fromBase64(
    INIT_CODE_BASE64[DEX_VERSION.v1_5].distributor
  ),
};
export const USER_DISTRIBUTOR_CODE: Record<DEX_VERSION, Cell> = {
  [DEX_VERSION.v1]: Cell.fromBase64(
    INIT_CODE_BASE64[DEX_VERSION.v1].user_distributor
  ),
  [DEX_VERSION.v1_5]: Cell.fromBase64(
    INIT_CODE_BASE64[DEX_VERSION.v1_5].user_distributor
  ),
};
