import { Cell } from '@ton/core';
import { DEX_VERSION } from '../types';

interface InitCodeBase64 {
  router: string;
  pool: string;
  account: string;
  positionnft: string;
  distributor: string;
  user_distributor: string;
}

const INIT_CODE_BASE64: Record<DEX_VERSION, InitCodeBase64> = {
  [DEX_VERSION.v1]: {
    router: process.env.ROUTER_CODE,
    pool: process.env.POOL_CODE,
    account:
      'te6cckECDQEAAloAART/APSkE/S88sgLAQIBYgIMAgLNAwsCtddtF2/ZkQ44BJL4HwaGmB9qJofSAA/DD9IAD8MWoYaH0AAPwx/QAA/DJ9AAD8Mv0AGHwzALjYSS+B8H0gGADpj+mf/CEpIGOCyJhxhvwgieOCyS+B8YbCB/l4QEBwLuIoIQPr5UMbqPa2wy+gD6APoA+gDTf9IX0hcw+ENQB6D4Y/hEUAWg+GQC+GX4ZiDCAPhD+EW+sPhE+Ea+sI6yghCBcC74yMsfFMs/+EP6AvhE+gL4Qc8WE8t/EsoXyhfJ+EIB2zxw+GNw+GRw+GVw+GaSXwTi4DAFBgAscYAYyMsFUAPPFnD6AhLLaszJgwb7AABCyPhD+gL4RPoC+EX6AvhG+gLJyPhBzxb4Qs8WzMntVNsxAl4gghBCoPtDuo6YWyCCCJiWgLzy4FOCCJiWgKH4QXDbPNsx4GwSghAL8/RHuuMCMAgJAChwgBjIywVQA88WUAP6AstqyQH7AAHc+EPCAPhEwgCx8uBQgg/ydhiCCA2J6HCCEIFwLvjIyx8Uyz/4Q/oC+ET6AvhBzxYTy38SyhfKF3D4QgLJEoBA2zxw+GNw+GRw+GVw+GbI+EP6AvhE+gL4RfoC+Eb6AsnI+EHPFvhCzxbMye1U2zEKACxxgBjIywVQBM8WUAT6AhLLaszJAfsAAEnThAEUcOgOmDgNUDiVk8T5BBh1hLVQBAiBDZSVUAcXJCB9hyGMAGWgonPaiaH0gAPww/SAA/DFqGGh9AAD8Mf0AAPwyfQAA/DL9ABh8M3wg/CF8IfwifCL8I0lL38n',
    positionnft:
      'te6cckECFwEAA3gAART/APSkE/S88sgLAQIBYgIQAgLLAw8CASAEDgIBIAUNAvXRkQ44BJL4HwaGmBgLjYSS+B8H0gfSAY/QAYuOuQ/QAY/QAYOdTaAHgHgWmP6Z+RQQhq9mUVXUcXGi2ZfCEsY4L5cMr9IAD8Mem/gPwy6QuA/DNpC4D8M+oYaGn/gPw0af+YfDT4CHARQQgv5h6KXXGBGhpBCCNlGa1dQGCQLYMvhDE8cF8uGR+kD6QNIAMfoAcCSBAU0B+kQwWLry9CDXScIA8uLEBoIK+vCAoYIImJaAoSGUUxWgod4i1wsBwwAgkgahkTbiIML/8uGSIZI2MOMN+EKCCJiWgIIQ9Ydg7/hByCbPFss/UmBwBwgAeoIQBRONkcj4Q88WUAjPFnElBEkTVEegcIAQyMsFUAfPFlAF+gIVy2oSyx/LPyJus5RYzxcBkTLiAckB+wAA3nCAEMjLBVAHzxZQBfoCFctqEssfyz8ibrOUWM8XAZEy4gHJAfsAA44+cCOBAU0B+kQwWLry9BOCENUydttQBG1xcIAQyMsFUAfPFlAF+gIVy2oSyx/LPyJus5RYzxcBkTLiAckB+wCSbDHi+GPwEAEQ4wJfA4QP8vAKAf4B+kDTf9IX0hfUMNDT/9P/MPhCF8cF8uBS+EMVxwXy4ZH4RhK68uGZ+Ee68uGZ+EXAAPLRmPhFAbYIIcjL/1Iwy//J+En4SMjL/8v/yfhH+Eb4RfhBghDXOsCdyMsfGss/+EPPFhnLPxjLfxfKFxbKF1Igy38VzBTMyfhFUAShCwEy+GX4aPhpgED4RcAAkzCDBt5w+EJa2zzwEAwALHGAGMjLBVAEzxZQBPoCEstqzMkB+wAASdOEARRw6A6YOA1QOJWTxPkEGHWEtVAECIENlJVQBxckIH2HIYwAZf9qJoaZ+A/DD9IAD8MX0gAPwx6gD8Mmm/gPwy6QuA/DNpC4D8M+oYaGn/gPw0af+YfDTABV0+En4SMjL/8v/yfhH+Eb4RfhE+EHIyz/4Qs8W+EPPFszLf8oXyhfMye1UgIBIBEUAgEgEhMAHbijjwD/hF+Eb4R/hI+EmAANueGfAP+EOAIBIBUWAHO4/P8A/4RNDTBzH0BDD4SfhI+Ef4RvhFcMjLBxb0ABXLfxTKFxPKFxLL/8v/yfhFwwD4QfhC+ENVA4AA26jC8A/4Qo1aJhlg==',
    distributor:
      'te6ccgECEQEAAhoAART/APSkE/S88sgLAQIBYgIDAgLLBAUCASANDgIBYgYHAgHOCwwB7UbCIg10nBYJFb4NMfAfhk0z8B+GYB0HTXIfpAMPhl7UTQ+kAB+GHUAfhj1DDQ9AQw+GL4RIIQp2neJ7rjAvhEghDw/r5kuo4s+EH4RccF8uK/0x/T/zDIy//4QhKAIPRD+GL4Qsj0AMn4Q8j4Qc8WzMzJ7VTgMICABvQgxJgwizbmFujPFo4pbSHBAJmALVADywcBo1jenAF6qQymMFhvAiHAAOYxmG8iAssHIW4S5jDigB0tMf03/U0/8wIdc5+EJSYIAg9A5vofLiw9P/MAHyqgHTBwHAA/Kr0/9ZuvKs1DBSEIMH9A5vofKt0x9SUrry4sTTf1JCuvLixfhFA/kAVBAlJfAQMzMB8BHHBfLiv/pA+kD6ADD4RgJwWQkBUHAgghAPin6lyMsfFss/UAP6AiHPFgHPFhPLAAH6AssAcAHJEoBC2zwKACxxgBjIywVQBM8WUAT6AhLLaszJAfsAADkcMjLAPgozxYUy/8Sy//LH8t/yfhDdsjLBMzMyYAAXPkAgwnIywrL/8nQgADW/cn9qJofSAA/DDqAPwx6hhoegIYfDF4CHgIwCAWYPEABJshs7UTQ+kAB+GHUAfhj1DDQ9AQw+GL4QoAg9A5vofLiw9P/MIAAxsn27UTQ+kAB+GHUAfhj1DDQ9AQw+GL4QYA==',
    user_distributor:
      'te6cckECCQEAAQUAART/APSkE/S88sgLAQIBIAIHAgFIAwYCAs4EBQABSABvQgxJgwizbmFujPFo4pbSHBAJmALVADywcBo1jenAF6qQymMFhvAiHAAOYxmG8iAssHIW4S5jDigAEaCY19qJoa4UAQH28mwhAYIQBfXhAL7y4sDtRNDSAAH4YfpAAfhi0/8B+GPT/wH4ZNMfAfhl038B+GbR+EHy0r5x+GH4RvhF+ET4Q/hByMsA+ELPFsv/y//LH8t/ye1U0z/UMCD5APhDuvLiwfgAggr68IBx+wL4RPhG+EWCEKdp3ifIyx8VCABCyz8Uyx8Ty3/My//JcYAQyMsF+ELPFnD6AstqzMmDBvsADs7vKQ==',
  },
  [DEX_VERSION.v1_6]: {
    router: process.env.ROUTER_CODE_V1_6,
    pool: process.env.POOL_CODE_V1_6,
    account:
      'te6cckECDAEAAtcAART/APSkE/S88sgLAQIBYgILAgLPAwkCiTtou37MiHHAJJfA+DQ0wMBcbCSXwPg+kgwAdMf0z/tRND6SPpI+gD6ANMf1PQE0VOlxwWRMOMNUZXHBZJfCuMNhA/y8IAQIAaIpghA+vlQxuo47OTk5BPoA+gBaoFBSoCTXScMAlzYDyM7JBQORNOJHZVUD8AEGyPpSFfpSUAP6AgH6AssfzPQAye1U2zHgKYIQodqpbbrjAjAFAdI5OTkE+kgx+kgx0x8x0z8x9AT0BDH0BNEhbpExjiYB0PpI+kj6APoAMAP5AQL5ARKhuMIAlROgUFKglxagUCWgUATiBOIgbpEw4w5HZVUD8AEGyPpSFfpSUAP6AgH6AssfzPQAye1U2zEGAW4H0CDXSgHSAzHIIs9BzgjQINdKAdIDdDIDobYIldQI9AAH5HQozzKhGM9AySfXSiDDAJIwN+MNBwCeyCHPQXRYoc9AGM7JKHGwc3LjBG1tyM+QOueBhinPCj8TywNwzwtHUmD6UhP0AM+H4BL0AM+QAAAAAvQAycjPhQhSMPpScc8LbszJgwb7AADMJ4IQQqD7Q7qOKRBIXwghggiYloC88uBTAYIImJaAocjPhYgS+lIB+gJwzwtqyXD7ANsx4DkGghBh2G/+uo4kA8jOyUdgEDVVA/ABBsj6UhX6UlAD+gIB+gLLH8z0AMntVNsx4F8IAfcIW6RMOAh0PoA+gDTP9MD0x/0BPQE9AT0BNEr0NdLMVL6uVLpuRixUoe5FrGSXwjgOClxsHNy4wQGwwBQCW3jBAjI9AAX9AAS9AAS9ADJbcjPkDrngYYVyj8TywNwzws/UAj6AlAG+gJSgPpSE/QAFcsDE/QAE8sf9ADJgCgBOyM+FCFIw+lJxzwtuzMmDBvsAcCBtbW1tA8j0ABL0APQA9ADJQTBtADOgonPaiaH0kfSR9AH0AaY+Y6noCkOhrpZiBX0QtBE=',
    positionnft:
      'te6cckECFQEABPgAART/APSkE/S88sgLAQIBYgIOAfbQ+JGOb9csJ/////Tyv9TUMdMHMdIfMdMAAZbTHzHTHzHe0SDQ1wsfghAGKozKuo5B7UTQ1j/6SPpI1NdM0AXQ1ywgMVRmVPK/10zQ9AXQBdN/BoEC9Nch9AHXCn+gyMt/Fc7JA8jOEvpS+lISzMzJ7VTgMOAgxwCRMOADBP74ku1E0ALTHwPTP/pI+kjU10wlwADjAgfTPyaCENXsyiq6jj4xMjQ1UgTHBfLhlQP6SNdM0NN/0hfSF9L/0v/0BNEFyMt/FMoXEsoXyv/K//QAyQTIyz8T+lIS+lLMzMntVOAmghBfzD0UuuMCJoIQRsozWrrjAiaCEAYqjMq6BAUICgDUMTQUxwXy4FIDi0YnVyboxwXy4Zr4l4IQBfXhAL7y4FPQ03/SF9IX0v8x0v8x9AQx0W3Iz4UIFfpSjQaAAAAAAAAAAAAAAAAAACmFr5YAAAAAAAAAAEDPFhXLPxLLf8oXEsoX9ADJgED7AAL4NviTcPg6UXPHBfLhkQX6SPpQ9AQx+gAg10ny4sQj+kQw8tFN+CdvEIIK+vCAoSKUUyqgod4jbrMgmST6RDDy0U0LoZE74iDC//LhkoIImJaAyM+FCFKQ+lIB+gKCEPWHYO/PC4oqzws/UlD6UinPCz/JcPsAIpI2W+MNBwYHAEjIz5AUTjZGKs8LPxf6Us7JyM+FCFJA+lJY+gJxzwtqzMlx+wAAXo4ayM+FCBf6Ulj6AoIQ1TJ2288LihTLP8lx+wCTNjQw4gHIyz/6UhL6UszMye1UAfw2BfpI03/SF9IX1AHQ0v/S/9EC9AVRyccF8uBS+CgmxwWTNSYF3lFXxwXy4ZEL0NN/0hfSF9L/0v9RdLry4ZlRUrry4Zkj8uGYUje2CFRzISrIyv9WEs8K/8lRdKEgwABwgA/jBFYQyMs/ywMUy38SyhfKFxjK/xXK/xP0ABMJAPTKf8ltbW0DyPQAEvQA9AD0AMltU6iAQCjAAJMwgwbeyM+QOueBhh/KP8+EYBLLP8+EAvpSEvQAz4Qg9ADPkAAAAAIb9ADJyM+FCFKA+lJxzwtuzMlQCfsAAcjLfxfKFxfKFxbK/xbK/xPOyQHIyz8S+lIT+lLMzMntVAHQ4wIyNgSCEMDFLju6jlUD+kjTAPQFB9DTf9IX0hfS/9cK/8jPk3t8emIbyz8X+lIY+lIWyz/LfxTKFxTKFwKXyMr/E8r/yZMwMm3iWPQAEvQAycjPhYgS+lJxzwtuzMmAQPsA4IQP8vALAf42BdcLf1FixwXy4FIl8uGbBtDTfyDSF9IX0v/S//QFK1F8oSDAAHCAD+MEgEAiwACTMIMG3izIyz8SywMZy38WyhcUyhcSyv/K//QAGMp/yW1tbQPI9AAS9AD0APQAyW3Iz5AYqjMqGMo/Js8LP1JA+lLMFvQAycjPhYhSQPpSDAFMic8Wc/oCcc8LZczJAfsABMjLfxPOyQHIyz8S+lIS+lISzMzJ7VQNAAEEAgEgDxICASAQEQAxuKOO1E0NQx10zQ03/SF9IX0v/S//QEMdGAAdueGe1E0NM/MfpIMfpIMIAgEgExQAfbj8/tRNDTP/pI+kjU10zQ03/SF9IX0v/S//QEMdEF0NMHMfQFyM+EAvQAJM8LfxPKF8oXy/8Sy//JAcMAVTCAAXuowu1E0NM/MfpIMI5xtAsQ==',
    distributor:
      'te6ccgECEQEAAhoAART/APSkE/S88sgLAQIBYgIDAgLLBAUCASANDgIBYgYHAgHOCwwB7UbCIg10nBYJFb4NMfAfhk0z8B+GYB0HTXIfpAMPhl7UTQ+kAB+GHUAfhj1DDQ9AQw+GL4RIIQp2neJ7rjAvhEghDw/r5kuo4s+EH4RccF8uK/0x/T/zDIy//4QhKAIPRD+GL4Qsj0AMn4Q8j4Qc8WzMzJ7VTgMICABvQgxJgwizbmFujPFo4pbSHBAJmALVADywcBo1jenAF6qQymMFhvAiHAAOYxmG8iAssHIW4S5jDigB0tMf03/U0/8wIdc5+EJSYIAg9A5vofLiw9P/MAHyqgHTBwHAA/Kr0/9ZuvKs1DBSEIMH9A5vofKt0x9SUrry4sTTf1JCuvLixfhFA/kAVBAlJfAQMzMB8BHHBfLiv/pA+kD6ADD4RgJwWQkBUHAgghAPin6lyMsfFss/UAP6AiHPFgHPFhPLAAH6AssAcAHJEoBC2zwKACxxgBjIywVQBM8WUAT6AhLLaszJAfsAADkcMjLAPgozxYUy/8Sy//LH8t/yfhDdsjLBMzMyYAAXPkAgwnIywrL/8nQgADW/cn9qJofSAA/DDqAPwx6hhoegIYfDF4CHgIwCAWYPEABJshs7UTQ+kAB+GHUAfhj1DDQ9AQw+GL4QoAg9A5vofLiw9P/MIAAxsn27UTQ+kAB+GHUAfhj1DDQ9AQw+GL4QYA==',
    user_distributor:
      'te6cckECCQEAAQUAART/APSkE/S88sgLAQIBIAIHAgFIAwYCAs4EBQABSABvQgxJgwizbmFujPFo4pbSHBAJmALVADywcBo1jenAF6qQymMFhvAiHAAOYxmG8iAssHIW4S5jDigAEaCY19qJoa4UAQH28mwhAYIQBfXhAL7y4sDtRNDSAAH4YfpAAfhi0/8B+GPT/wH4ZNMfAfhl038B+GbR+EHy0r5x+GH4RvhF+ET4Q/hByMsA+ELPFsv/y//LH8t/ye1U0z/UMCD5APhDuvLiwfgAggr68IBx+wL4RPhG+EWCEKdp3ifIyx8VCABCyz8Uyx8Ty3/My//JcYAQyMsF+ELPFnD6AstqzMmDBvsADs7vKQ==',
  },
};

export const ROUTER_CODE: Record<DEX_VERSION, Cell> = {
  [DEX_VERSION.v1]: Cell.fromBase64(INIT_CODE_BASE64[DEX_VERSION.v1].router),
  [DEX_VERSION.v1_6]: Cell.fromBase64(
    INIT_CODE_BASE64[DEX_VERSION.v1_6].router
  ),
};
export const ACCOUNT_CODE: Record<DEX_VERSION, Cell> = {
  [DEX_VERSION.v1]: Cell.fromBase64(INIT_CODE_BASE64[DEX_VERSION.v1].account),
  [DEX_VERSION.v1_6]: Cell.fromBase64(
    INIT_CODE_BASE64[DEX_VERSION.v1_6].account
  ),
};
export const POSITION_CODE: Record<DEX_VERSION, Cell> = {
  [DEX_VERSION.v1]: Cell.fromBase64(
    INIT_CODE_BASE64[DEX_VERSION.v1].positionnft
  ),
  [DEX_VERSION.v1_6]: Cell.fromBase64(
    INIT_CODE_BASE64[DEX_VERSION.v1_6].positionnft
  ),
};
export const POOL_CODE: Record<DEX_VERSION, Cell> = {
  [DEX_VERSION.v1]: Cell.fromBase64(INIT_CODE_BASE64[DEX_VERSION.v1].pool),
  [DEX_VERSION.v1_6]: Cell.fromBase64(INIT_CODE_BASE64[DEX_VERSION.v1_6].pool),
};
export const DISTRIBUTOR_CODE: Record<DEX_VERSION, Cell> = {
  [DEX_VERSION.v1]: Cell.fromBase64(
    INIT_CODE_BASE64[DEX_VERSION.v1].distributor
  ),
  [DEX_VERSION.v1_6]: Cell.fromBase64(
    INIT_CODE_BASE64[DEX_VERSION.v1_6].distributor
  ),
};
export const USER_DISTRIBUTOR_CODE: Record<DEX_VERSION, Cell> = {
  [DEX_VERSION.v1]: Cell.fromBase64(
    INIT_CODE_BASE64[DEX_VERSION.v1].user_distributor
  ),
  [DEX_VERSION.v1_6]: Cell.fromBase64(
    INIT_CODE_BASE64[DEX_VERSION.v1_6].user_distributor
  ),
};
