import { Cell } from '@ton/core';

const INIT_CODE_BASE64 = {
  router: process.env.ROUTER_CODE,
  pool: process.env.POOL_CODE,
  account: process.env.ACCOUNT_CODE,
  positionnft: process.env.POSITION_CODE,
  distributor:
    'te6ccgECEQEAAhoAART/APSkE/S88sgLAQIBYgIDAgLLBAUCASANDgIBYgYHAgHOCwwB7UbCIg10nBYJFb4NMfAfhk0z8B+GYB0HTXIfpAMPhl7UTQ+kAB+GHUAfhj1DDQ9AQw+GL4RIIQp2neJ7rjAvhEghDw/r5kuo4s+EH4RccF8uK/0x/T/zDIy//4QhKAIPRD+GL4Qsj0AMn4Q8j4Qc8WzMzJ7VTgMICABvQgxJgwizbmFujPFo4pbSHBAJmALVADywcBo1jenAF6qQymMFhvAiHAAOYxmG8iAssHIW4S5jDigB0tMf03/U0/8wIdc5+EJSYIAg9A5vofLiw9P/MAHyqgHTBwHAA/Kr0/9ZuvKs1DBSEIMH9A5vofKt0x9SUrry4sTTf1JCuvLixfhFA/kAVBAlJfAQMzMB8BHHBfLiv/pA+kD6ADD4RgJwWQkBUHAgghAPin6lyMsfFss/UAP6AiHPFgHPFhPLAAH6AssAcAHJEoBC2zwKACxxgBjIywVQBM8WUAT6AhLLaszJAfsAADkcMjLAPgozxYUy/8Sy//LH8t/yfhDdsjLBMzMyYAAXPkAgwnIywrL/8nQgADW/cn9qJofSAA/DDqAPwx6hhoegIYfDF4CHgIwCAWYPEABJshs7UTQ+kAB+GHUAfhj1DDQ9AQw+GL4QoAg9A5vofLiw9P/MIAAxsn27UTQ+kAB+GHUAfhj1DDQ9AQw+GL4QYA==',
  user_distributor:
    'te6cckECCQEAAQUAART/APSkE/S88sgLAQIBIAIHAgFIAwYCAs4EBQABSABvQgxJgwizbmFujPFo4pbSHBAJmALVADywcBo1jenAF6qQymMFhvAiHAAOYxmG8iAssHIW4S5jDigAEaCY19qJoa4UAQH28mwhAYIQBfXhAL7y4sDtRNDSAAH4YfpAAfhi0/8B+GPT/wH4ZNMfAfhl038B+GbR+EHy0r5x+GH4RvhF+ET4Q/hByMsA+ELPFsv/y//LH8t/ye1U0z/UMCD5APhDuvLiwfgAggr68IBx+wL4RPhG+EWCEKdp3ifIyx8VCABCyz8Uyx8Ty3/My//JcYAQyMsF+ELPFnD6AstqzMmDBvsADs7vKQ==',
};

export const ROUTERV3_CODE = Cell.fromBase64(INIT_CODE_BASE64.router);
export const ACCOUNTV3_CODE = Cell.fromBase64(INIT_CODE_BASE64.account);
export const POSITIONV3_CODE = Cell.fromBase64(INIT_CODE_BASE64.positionnft);
export const POOLV3_CODE = Cell.fromBase64(INIT_CODE_BASE64.pool);

export const DISTRIBUTOR_CODE = Cell.fromBase64(INIT_CODE_BASE64.distributor);
export const USER_DISTRIBUTOR_CODE = Cell.fromBase64(
  INIT_CODE_BASE64.user_distributor
);
